version: '3.1'

services:

  dbperfil:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - c:\chat\perfil\db:/data/db
    networks:
      - chat

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@dbperfil:27017/
    networks:
      - chat
  
  profile-api:
    build: .\chat-perfil-api

networks:
  chat:
    driver: bridge